services:
  mongo:
    image: mongo:8.0.11
    container_name: linetree-mongo
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - ./docker-files/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

  mongo-express:
    image: mongo-express:1.0.2
    container_name: linetree-mongo-express
    restart: always
    ports:
      - '8082:8081'
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo

  graphdb:
    image: ontotext/graphdb:10.8.8
    container_name: linetree-graphdb
    ports:
      - '7200:7200'
    volumes:
      - ./docker-files/graphdb:/opt/graphdb/home

  gateway:
    build:
      context: ./backend
      dockerfile: apps/gateway/Dockerfile
    container_name: linetree-gateway
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - graphdb
      - users
      - genealogy
    environment:
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
      - GATEWAY_SERVICE_PORT=${GATEWAY_SERVICE_PORT}
      - JWT_COOKIE_MAX_AGE=${JWT_COOKIE_MAX_AGE}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - GENEALOGY_SERVICE_HOST=${GENEALOGY_SERVICE_HOST}
      - GENEALOGY_SERVICE_PORT=${GENEALOGY_SERVICE_PORT}
      - USER_SERVICE_HOST=${USER_SERVICE_HOST}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}

  users:
    build:
      context: ./backend
      dockerfile: apps/users/Dockerfile
    container_name: linetree-users
    environment:
      - USER_SERVICE_HOST=${USER_SERVICE_HOST}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - MONGODB_URI=${MONGODB_URI}

  genealogy:
    build:
      context: ./backend
      dockerfile: apps/genealogy/Dockerfile
    container_name: linetree-genealogy
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - GENEALOGY_SERVICE_PORT=${GENEALOGY_SERVICE_PORT}
      - GENEALOGY_SERVICE_HOST=${GENEALOGY_SERVICE_HOST}
      - RDF_BASE_URL=${RDF_BASE_URL}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_BASE_URL: ${BACKEND_BASE_URL}
    container_name: linetree-frontend
    ports:
      - '8085:80'
